### ISSUE TITLE
Feature Request: Prev and Next Buttons

### ISSUE THREAD

**Issue by snnsnn** [rescript-association/rescript-lang.org#601]
It is really cumbersome to navigate docs in sequential manner. Please can you add PREV and NEXT buttons to the website (both on the top and the bottom of the page if possible). Strong connection and easy navigation improves spatial memory, bolster learning and recollection, especially on re-visits. I am sure it will help with the adoption rate.

Something like the ones on this page: https://www.typescriptlang.org/docs/handbook/2/basic-types.html. And maybe with simple or less intrusive top buttons which is missing on the above link.

Thank you.

**Comment by kswope** [comment]
Came here to file this issue but found it already at the top of the list.

If you are looking up something there's no need for prev-next navigation, but if you are learning rescript and reading the docs like a book, its a very frustrating experience, especially since its difficult to find out where you currently are so you can find the next section (maybe that only happens on a small screen like a laptop)

OP gave an example of the typescript docs.  Even better, how about the website this one was cloned from?

https://reasonml.github.io/docs/en/overview
