### ISSUE TITLE
Integrate genType docs into main docs as "TypeScript interop"

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-association/rescript-lang.org#746]
genType has moved into the compiler since 10.1 and flow support has been dropped

Let's move its docs into the main section as "TypeScript interop". Remove all mentions of "flowtype" and "Reason" and update the docs.

**Comment by cometkim** [comment]
IMHO TypeScript interop shouldn't be treated as special. Except for gentype-specific config, most of it is required for general JS codebase interoperability. Instead, we can say that TypeScript is supported natively.

Instead of the "TypeScript interop" chapter, I suggest providing more generally useful guides in a "Working with JavaScript/TypeScript projects" chapter.

For example, https://rescript-collection.pages.dev/docs/javascript#pipe-operator describes how dealing with pipe patterns in JS codebase.

**Comment by fhammerschmidt** [comment]
Moving those issues over from #697
- [ ] GenType: Add `moduleResolution` option to customize extensions on emitted import statements. This helps to adjust output compatibility with TypeScript projects using ESM. https://github.com/rescript-lang/rescript-compiler/pull/6182
  - `node` (default): Drop extensions.
  - `node16`: Use TS output's extensions. Make it ESM-compatible.
  - `bundler`: Use TS input's extensions. Make it ESM-compatible.
- [ ] GenType: add the option to use the `@genType` annotation at the module level, meaning that all the items in the module should be exported. https://github.com/rescript-lang/rescript-compiler/pull/6113
- [ ] GenType: add support for `@genType` annotations on module definitions. https://github.com/rescript-lang/rescript-compiler/pull/6113
- [ ] GenType: removed support for `@genType.as` for records and variants which has become unnecessary. Use the language's `@as` instead to channge the runtime representation without requiring any runtime conversion during FFI. https://github.com/rescript-lang/rescript-compiler/pull/6099 https://github.com/rescript-lang/rescript-compiler/pull/6101
