### ISSUE TITLE
"Undocumented" breaking change of array access in v11

### ISSUE THREAD

**Issue by l2dy** [rescript-association/rescript-lang.org#825]
The following code compiles in v10, but not in v11.

https://rescript-lang.org/try?version=v11.0.1&code=DYUwLgBAhhC8EG0AMAaCBGAugKFJA+nBAFIDOAdAJIB2Y5YA9gKIAeADg9SLQJZTAAKKMkwBKIA

```rescript
let a = [0, 1]
let _ = Js.Int.toExponential(a[0])
```

```
[E] Line 2, column 29:

This has type: option<int>
  But this function argument is expecting: int
```

This change does not appear in https://rescript-lang.org/docs/manual/latest/migrate-to-v11#list-of-all-breaking-changes, but is discussed [on the forum](https://forum.rescript-lang.org/t/resscript-v11-0-0-rc-8-array-access-type-errors/4966/2).

Ref #743

**Comment by fhammerschmidt** [comment]
I admit this change is kinda hidden, since it's suggested to switch to the new standard library "ReScript Core" and open that by default. But the migration guide refers to the migration docs of ReScript Core which cover that, albeit briefly.

When you only use the playground, it totally looks like a hard breaking change since it automatically uses and opens ReScript Core for when v11 is selected. But the migration guide is actually not for the playground which also includes some other hacks to be able to run the compiler without a build system in the browser.

It's not in the list of breaking changes since those are only the ones from the compiler, they don't cover the switch from the old OCaml standard library (or ReScript's own Belt library) to ReScript Core. This will only actually be a breaking change when ReScript Core will be part of the compiler in v12.

**Comment by l2dy** [comment]
> I admit this change is kinda hidden, since it's suggested to switch to the new standard library "ReScript Core" and open that by default. But the migration guide refers to the migration docs of ReScript Core which cover that, albeit briefly.
> 
> When you only use the playground, it totally looks like a hard breaking change since it automatically uses and opens ReScript Core for when v11 is selected. But the migration guide is actually not for the playground which also includes some other hacks to be able to run the compiler without a build system in the browser.

I followed https://rescript-lang.org/docs/manual/latest/installation to initialize a project from scratch and migrated code over, but I understand that it's an unusual migration path.

Without going through the guide in depth, it looks more like a language change than what a library would do. Believing so, I only searched for keywords like array access and `[` in the compiler part, but to no avail.

> It's not in the list of breaking changes since those are only the ones from the compiler, they don't cover the switch from the old OCaml standard library (or ReScript's own Belt library) to ReScript Core. This will only actually be a breaking change when ReScript Core will be part of the compiler in v12.

It's technically correct to do so, but I think it won't hurt to list language changes as an example of breaking changes in the ReScript Core section.
