### ISSUE TITLE
Missing curlies when piping from `await`?

### ISSUE THREAD

**Issue by psb** [rescript-association/rescript-lang.org#837]
Does the `await response` in [this line](https://github.com/rescript-association/rescript-lang.org/blob/e0b809aab64a610868e251c931782a7912037ad8/pages/docs/manual/latest/async-await.mdx?plain=1#L311):

`let data = await response->Response.json`

need to be wrapped in curly braces:

`let data = {await response}->Response.json`

as explained in the previous section about piping the result of an `await` call into a function?

**Comment by fhammerschmidt** [comment]
No. Those are two different things.

As you can see the response is already a resolved Promise value, as it was called with await. Thus its type is `Response.t<'data>`.

The second await is because of an asynchronous JSON decoding function. So it's equivalent to

`let data = await {response->Response.json}`

**Comment by psb** [comment]
Ah, okay. Thanks.
